import * as dao from "./dao.js";
import * as foldersDao from "../Folders/dao.js";

// The following functions use try catch blocks generated by GitHub Copilot
export default function PostRoutes(app) {
    const getPosts = async (req, res) => {
        const posts = await dao.getPosts();
        res.json(posts);
    }

    const getPostsByCourseId = async (req, res) => {
        const courseId = req.params.cid;
        if (!courseId) {
            res.status(400).send("Course ID is required");
            return;
        }
        const posts = await dao.getPostsByCourseId(courseId);
        res.json(posts);
    }

    const getPostsByContent = async (req, res) => {
        const { content } = req.query;
        const { cid } = req.params;
        console.log(`Searching for posts with content: ${content} in course ID: ${cid}`);
        if (!content) {
            res.status(400).send("Content query parameter is required");
            return;
        }
        try {
            const posts = await dao.getPostsByContent(content, cid);
            res.json(posts);
        } catch (error) {
            res.status(500).send("Error retrieving posts by content");
        }
    }

    const getPostsByFolderId = async (req, res) => {
        const {folder} = req.params;
        if (!folder) {
            res.status(400).send("Folder ID is required");
            return;
        }
        try {
            const posts = await dao.getPostsByFolderId(folder);
            res.json(posts);
        } catch (error) {
            res.status(500).send("Error retrieving posts by folder ID");
        }
    }

    const getPostsByPostId = async (req, res) => {
        console.log();
        const postId = req.params.pid;
        console.log(`Post ID: ${postId}`);
        if (!postId) {
            res.status(400).send("Post ID is required");
            return;
        }
        try {
            const post = await dao.getPostsByPostId(postId);
            res.json(post);
        } catch (error) {
            res.send("Error retrieving post by ID");
        }
    }

    const createPost = async (req, res) => {
        const postData = req.body;
        try {
            const newPost = await dao.createPost(postData);
            return res.send(newPost);
        } catch (error) {
            res.send("Error creating post");
        }
    }

    const updatePost = async (req, res) => {
        const postId = req.params.pid;
        const postData = req.body;
        if (!postId || !postData) {
            res.status(400).send("Post ID and data are required");
            return;
        }
        try {
            const updatedPost = await dao.updatePost(postId, postData);
            if (!updatedPost) {
                res.status(404).send("Post not found");
                return;
            }
            res.json(updatedPost);
        } catch (error) {
            res.status(500).send("Error updating post");
        }
    }

    const deletePost = async (req, res) => {
        console.log("Deleting post");
        const postId = req.params.pid;
        if (!postId) {
            res.status(400).send("Post ID is required");
            return;
        }
        try {
            const result = await dao.deletePost(postId);
            if (result.deletedCount === 0) {
                res.status(404).send("Post not found");
                return;
            }
            res.sendStatus(204); // No content
        } catch (error) {
            console.error(error); // log actual error
            res.status(500).send("Error deleting post");
        }
    };

    const getFoldersByCourseId = async (req, res) => {
        const courseId = req.params.cid;
        if (!courseId) {
            res.status(400).send("Course ID is required");
            return;
        }
        try {
            const folders = await foldersDao.getFoldersByCourseId(courseId);
            res.json(folders);
        } catch (error) {
            res.status(500).send("Error retrieving folders by course ID");
        }
    }

    const addFolder = async (req, res) => {
        const folderData = req.body;
        if (!folderData || !folderData.name || !folderData.cid) {
            res.status(400).send("Folder name and course ID are required");
            return;
        }
        try {
            const newFolder = await foldersDao.createFolder(folderData);
            res.status(201).json(newFolder);
        } catch (error) {
            res.status(500).send("Error creating folder");
        }
    }

    const updateFolder = async (req, res) => {
        const folderId = req.params.fid;
        const folderData = req.body;
        if (!folderId || !folderData) {
            res.status(400).send("Folder ID and data are required");
            return;
        }
        try {
            const updatedFolder = await foldersDao.updateFolder(folderId, folderData);
            if (!updatedFolder) {
                res.status(404).send("Folder not found");
                return;
            }
            res.json(updatedFolder);
        } catch (error) {
            res.status(500).send("Error updating folder");
        }
    }

    const deleteFolder = async (req, res) => {
        const folderId = req.params.fid;
        if (!folderId) {
            res.status(400).send("Folder ID is required");
            return;
        }
        try {
            const result = await foldersDao.deleteFolder(folderId);
            if (result.deletedCount === 0) {
                res.status(404).send("Folder not found");
                return;
            }
            res.sendStatus(204); // No content
        } catch (error) {
            res.status(500).send("Error deleting folder");
        }
    }

    app.get("/api/courses/piazza/posts", getPosts);
    app.get("/api/courses/piazza/posts/:cid", getPostsByCourseId);
    app.get("/api/courses/piazza/posts/search/:cid", getPostsByContent);
    app.get("/api/courses/piazza/posts/folder/:folder", getPostsByFolderId);
    app.get("/api/courses/piazza/posts/post/:pid", getPostsByPostId);
    app.post("/api/courses/piazza/posts", createPost);
    app.put("/api/courses/piazza/posts/:pid", updatePost);
    app.delete("/api/courses/piazza/posts/:pid", deletePost);
    app.get("/api/courses/piazza/folders/:cid", getFoldersByCourseId);
    app.post("/api/courses/piazza/folders", addFolder);
    app.put("/api/courses/piazza/folders/:fid", updateFolder);
    app.delete("/api/courses/piazza/folders/:fid", deleteFolder);
}